### PR TITLE
Replace os model (from huggingface) with TDApiClient in-db function

### PR DESCRIPTION
**Pull request by chetan-hirapara**
Hi Team,

Please review this PR.

**Task:** https://github.com/Teradata/jupyter-demos/issues/627
------------------------
**Task Description:** 

Use TDApiClient instead of directly calling openai functions on the below usecase:

1. Chat_with_docs_VantageDB_GenAI_Python
2. Chat_powered_product_recommendation_based_on_search_output
3. Natural_Language_Processing_Python.ipynb

### CODE REVIEW

**Comment by ForbiddenDevil** [comment]
Peer-Review completed.

**Comment by chetan-hirapara** [comment]
@DallasBowden - Please review this PR, peer review is already done by Pratik

**Comment by chetan-hirapara** [comment]
@DallasBowden - Please review this PR, I have made required changes and it should running top to bottom now. 

I would advise to create a new machine and take the latest code from "**tdapiclient_replace_os_model**"

**Review by DallasBowden — APPROVED** [review]
All notebooks are executing as expected.

**Pull request merged**
