### PR TITLE
Consumer complaints with google gemini

### PR DESCRIPTION
**Pull request by chetan-hirapara**
Consumer complaints with google gemini

Task: https://github.com/Teradata/jupyter-demos/issues/679

### CODE REVIEW

**Comment by ForbiddenDevil** [comment]
All UseCases run fine.

**Comment by chetan-hirapara** [comment]
@DallasBowden - Please review this PR, peer review is done by Pratik.

**Comment by chetan-hirapara** [comment]
@DallasBowden - updated the demo links in Complaints_Analysis_GenAI_Bedrock/Complaint_Analysis_Dashboard.ipynb,

Please check and review it.

**Comment by chetan-hirapara** [comment]
@DallasBowden - please review this PR.

**Comment by chetan-hirapara** [comment]
@DallasBowden - I haved updated the msg **Now the results can be saved back to Vantage.** - please verify it once again and review this PR

**Pull request merged**
