### PR TITLE
Marketing campaign effectiveness

### PR DESCRIPTION
**Pull request by chetan-hirapara**
Task# https://github.com/Teradata/jupyter-demos/issues/286

Task description: who to target for a product based on prior success/failure ... business value is reduced cost and annoyance of customer

@DougEbel @ForbiddenDevil - please review this PR.

### CODE REVIEW

**Comment by DougEbel** [comment]
I'll repeat this comment in e-mail.  Not sure if pratik will get an e-mail from comment in github.  

1. do restart kernel/clear outputs before saving.  Notebooks shouldn't have graphs/tables or user won't know they are running anything. 
2. spotted some spelling issues
3. ran all steps and got "NameError: name 'CategoricalSummary' is not defined"  

Stopping review. I'll let Pratik and you work on this before my full review.

**Comment by chetan-hirapara** [comment]
@DougEbel - Please take a moment to review this PR. Pratik has finished the review, and I updated those suggestions to the notebook.

cc: @ForbiddenDevil

**Comment by DougEbel** [comment]
I'm impressed with this "from scratch" demo. I'd like you to think about the reality of some of the data and have some compassion for the person that opens up this demo and doesn't have a data science background. 

1. WOW:  campaign_33, campaign_27, campaign_41, and campaign_26,campaign_29 have a 100% purchase rate. ... hire that marketing person.  What yields that besides coupons sitting on the cash register that are scanned when the user checks out?  
2. Ugh:  The non-purchase rate for campaigns like campaign_31, campaign_25, campaign_43, campaign_20, campaign_63, campaign_23, campaign_28, and campaign_32 is 100 percent.  ... fire that marketing person.   ... if you didn't manipulate this outcome and got the data from kaggle, then confess the "interesting outcome". 
3. Effects on campaign purchase ... up to 58 of Previous contacts performed?  really?  after about 5 I'd tell the customer to go pound salt 
4. In 4.2 you show 7 graphs with the  description:  "From the above results, we see some of the features are right skewd like age, last_contact_duration and prev_contacts_performed. while recency seems near to normal distribution."  ... I don't get how you came to that conclusion  (describe how you look at the shapes, then give a bulleted list or table for each graph and the conclusion based on your approach to assessing the shape of the plot.  
5. in 4.3, you say " Measuring correlation lets you determine if the value of one variable is useful in predicting the value of another."  give an example
6. Again, in 4.5 Outlier Analysis, say what the basis of your examination of the graphs to come up with the conclusion. 
7.  in 4.6 Data Transformation, we do this work to create ______ ? at the end you say "Save the transformed dataframe into a table marketing_campaign_trans_data" ... but you needed to start with a description of the real-world implication of the resulting data. 
8. No description  following the confusion matrix.  the description appears to precede.  The preceding description should say what a confusion matrix is for.  When you move the conclusions following the matrix, give the total of all purchase/not purchase and  describe the cells with counts followed by the percentages in  ( ).  
9. Are there visualizations available that we could use to graphically differentiate xgboost from decision tree?  Being a "skimmer of text", ... but going back to reread, I'm not sure I'm getting the difference.

**Comment by chetan-hirapara** [comment]
> I'm impressed with this "from scratch" demo. I'd like you to think about the reality of some of the data and have some compassion for the person that opens up this demo and doesn't have a data science background.
> 
> 1. WOW:  campaign_33, campaign_27, campaign_41, and campaign_26,campaign_29 have a 100% purchase rate. ... hire that marketing person.  What yields that besides coupons sitting on the cash register that are scanned when the user checks out?
  * This was due to less no of contacts perfomed during that perticular campaign and all the contacted clients has purchased a product.
> 2. Ugh:  The non-purchase rate for campaigns like campaign_31, campaign_25, campaign_43, campaign_20, campaign_63, campaign_23, campaign_28, and campaign_32 is 100 percent.  ... fire that marketing person.   ... if you didn't manipulate this outcome and got the data from kaggle, then confess the "interesting outcome".
* Yes this data is taken from kaggle only. The reason for non purhase rate 100% is same as above. less no of conatcts performed and contacted clients didn't made a purchase.
> 3. Effects on campaign purchase ... up to 58 of Previous contacts performed?  really?  after about 5 I'd tell the customer to go pound salt
 * Simplified the grpah now. Only added purchaed records. As this is kaggle data, it might be not the real one.
> 4. In 4.2 you show 7 graphs with the  description:  "From the above results, we see some of the features are right skewd like age, last_contact_duration and prev_contacts_performed. while recency seems near to normal distribution."  ... I don't get how you came to that conclusion  (describe how you look at the shapes, then give a bulleted list or table for each graph and the conclusion based on your approach to assessing the shape of the plot.
* Added description
> 5. in 4.3, you say " Measuring correlation lets you determine if the value of one variable is useful in predicting the value of another."  give an example
* Added description and example
> 6. Again, in 4.5 Outlier Analysis, say what the basis of your examination of the graphs to come up with the conclusion.
* Added description
> 7. in 4.6 Data Transformation, we do this work to create ______ ? at the end you say "Save the transformed dataframe into a table marketing_campaign_trans_data" ... but you needed to start with a description of the real-world implication of the resulting data.
* Added description - about why we have to do data transformation
> 8. No description  following the confusion matrix.  the description appears to precede.  The preceding description should say what a confusion matrix is for.  When you move the conclusions following the matrix, give the total of all purchase/not purchase and  describe the cells with counts followed by the percentages in  ( ).
* Added description for confusion matrix and conclusions as well
> 9. Are there visualizations available that we could use to graphically differentiate xgboost from decision tree?  Being a "skimmer of text", ... but going back to reread, I'm not sure I'm getting the difference.
* Here both Algos are performing nearly the same. So it is hard to tell which one is better. I have already added graph for comparing the metrics and AUC-ROC values.

**Comment by chetan-hirapara** [comment]
@DougEbel - Please review it once again.

**Comment by DougEbel** [comment]
I used a machine with all of the all of the newer libraries and encountered 2 errors on running all steps:

after the imports:
/opt/conda/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.25.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

in 4.3, after "get_heatmap(df)"
ValueError: could not convert string to float: 'entrepreneur'

On the "Impact of Previous Campaign on Purchase" graph, the  X axis still goes out to  55.    I think a max of 10 is enough and doesn't raise as many questions on the data.

I didn't do a throrough review of your added comments due to the errors in case I didn't get everything you had updated.  Below is the steps I did before running all steps. 


(base) jovyan@9e000779ba8a:~/JupyterLabRoot$ git switch marketing_campaign
M       Teradata/Config/userinfo.db
Switched to branch 'marketing_campaign'
Your branch is behind 'origin/marketing_campaign' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
(base) jovyan@9e000779ba8a:~/JupyterLabRoot$ git pull
Updating 1632671..cbf3098
Fast-forward
 UseCases/Marketing_Campaign_Effectiveness/Marketing_Campaign_Effectiveness_Preditction_PY_SQL.ipynb | 281 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------------------------
 1 file changed, 206 insertions(+), 75 deletions(-)

**Comment by DougEbel** [comment]
Will look at more detail next time.

**Comment by chetan-hirapara** [comment]
Hi @DougEbel 

* This is working fine on new machine. Today I have created a new machine and ran the entire notebook. It is working fine without any error.
* Also, to verify on another machine, I asked to Pratik to run the same notebook. It is working fine on his machine as well.
* Well, I have added limits on number of campaings to show on x-axis to 10 in the Impact of Previous Campaign on Purchase graph
* Please run it on new machine and review it.

cc: @ForbiddenDevil

**Review by DougEbel — APPROVED** [review]
In 3.1.8, I still have a problem with graph and your conclusion: "If multiple campaigns and multiple contacts are performed for the clients, there is a greater chance for the client to not be interested in purchasing the product. At least 2 or 3 contacts can be preferred to perform for the clients.  Looks to me like if the number of prior contacts was 0, you get the most purchases and that the yield even after 1 prior contact isn't worth it. 

That is not a show stopper but if that part of the analysis doesn't produce explainable results, drop it since you've lots of other great stuff.

**Pull request merged**
