### PR TITLE
Vehicle route delivery - initial draft

### PR DESCRIPTION
**Pull request by shilpa-nalkande**
Vehicle Routing Delivery Demo

### CODE REVIEW

**Comment by DallasBowden** [comment]
6. Using Script Command to get the forecasted values back to Vantage.
image

OperationalError: [Version 17.20.0.0] [Session 1118] [Teradata Database] [Error 9852] The file DEMO_USER.MILP_continuous does not exist in the datab
image
ase.

**Review by DallasBowden — COMMENTED** [review]
I'm getting this error message:
image

**Review by DallasBowden — APPROVED** [review]
The notebook ran fine.

**Comment by DougEbel** [comment]
I spotted one misspelling.  The maps of the routes for each truck at the end appear to be identical. There are colors on some lines and some numbers on some lines but no explanations of what they mean.  And, if this is a routing application, how do I know what is first, second ... nth stop on the delivery route?

**Pull request merged**
