### PR TITLE
New usecase using Hyperparameter tuning

### PR DESCRIPTION
**Pull request by shilpa-nalkande**
Currently using python functions for roc, will replace with teradataml function after issue is resolved

### CODE REVIEW

**Comment by shilpa-nalkande** [comment]
Added Business-Value props but not sure about filters and Related Resources. Need inputs for Related Resources

**Review by DallasBowden — CHANGES_REQUESTED** [review]
Can we rename this folder.  It needs to have Hyperparameter and Titanic in the name to help it stand out in the list of use case folders.

Underscores are showing up in the Introduction:
"Researchers are still drawn to the Titanic disaster, even though it happened just over a century ago, as they try to figure out _how some people survived while others couldn't_. "

Why Teradata?   First line doesn't need a bullet.

**Comment by shilpa-nalkande** [comment]
Changed folder name and corrected the Introduction as per review comments.

**Comment by DallasBowden** [comment]
I updated the dataset details.  I'm giving this to Kevin to review.

**Review by DallasBowden — APPROVED** [review]
I deleted the original folder and notebook.
I've added the Beta introduction to the top of the notebook.

**Comment by DallasBowden** [comment]
I deleted the original folder and notebook file.  I've added the Beta Paragraph to the top of the notebook.

**Pull request merged**
