### PR TITLE
pass6 changes for telco network coverage

### PR DESCRIPTION
**Pull request by nupur-lal**

### CODE REVIEW

**Review by DallasBowden — CHANGES_REQUESTED** [review]
"we measure the signal strength in RSCP" --- capitalize the W at the beginning of the sentence.

"We have categorized the signal strength in poor, good and excellent based on the dBm values" --- add a period to the end of the sentence.

"From this table we can create 1 row for each customer journey trajectory using Vantage ClearScape Analytics UAF(unbounded array framework) . UAF is the Teradata framework for building end-to-end time series forecasting pipelines. For further information on UAF, please [refer here]"  --- add a seperator between this and the next line.
TRACKINGOP is a multi-dimensional function for geospatial data in UAF which can calculate trip distance, speed, time for a trip. It helps users to optimize their resources by providing insights into the movements of their assets. For example, by tracking the ...

I didn't get the drop-down.
image

**Comment by nupur-lal** [comment]
@DallasBowden incorporated the format comments. For the plot , I  havent changed anything from the previous notebook ; the map is displaying on my vm..network issue may be?

**Comment by DallasBowden** [comment]
This is working for me now.  However, I don't see a card for it on the Kanban -- only 483.  I'm adding it to the list for Kevin to look at.

**Review by DallasBowden — APPROVED** [review]
1. We don't have to say "Vantage ClearScape Analytics", just "ClearScape Analytics.
2. Changed "UAF is the Teradata framework" to "UAF is the Vantage framework".

Approved and Merged.

**Pull request merged**
