### PR TITLE
Add SQLAgent for enhance the query generation in Question Answering demo

### PR DESCRIPTION
**Pull request by chetan-hirapara**
Hi Team,

Please review this PR.

**Description**: In Generative AI Question Answering demo we have older version of Lanchain code, that needs to update with latest features like SQLAgent

-------------------------------------

**Task**: https://github.com/Teradata/jupyter-demos/issues/642

### CODE REVIEW

**Comment by chetan-hirapara** [comment]
@DallasBowden - Please review this PR, team peer review is done by Pratik

**Comment by ForbiddenDevil** [comment]
Peer-Review completed.

**Comment by chetan-hirapara** [comment]
@DallasBowden - Please review this PR, peer review is already done by Pratik

**Review by DallasBowden — APPROVED** [review]
Executes as expected.

**Pull request merged**
