### PR TITLE
Trusted AI: Gen AI Mortage calculator - Finetune model

### PR DESCRIPTION
**Pull request by chetan-hirapara**
Hi @DallasBowden 

Please review this PR. 

Task# https://github.com/Teradata/jupyter-demos/issues/620

### CODE REVIEW

**Comment by chetan-hirapara** [comment]
@DallasBowden - I haved added missed `import time` into fine tune demo.

Please verify it once and let me know more changes.

**Comment by chetan-hirapara** [comment]
@DallasBowden - Added notes before launching the chatbot

image

**Comment by chetan-hirapara** [comment]
@DallasBowden - Added few changes to reduce appology message. Please review this PR once again

**Review by DallasBowden — APPROVED** [review]
Beta paragraphs added.  Job.id updated to job_id.  One sample question removed.

**Pull request merged**
