### PR TITLE
Added grocery recommendation usecase

### PR DESCRIPTION
**Pull request by ForbiddenDevil**
@DallasBowden @pranaydave Please review.

### CODE REVIEW

**Comment by DallasBowden** [comment]
I've added my review comments into a document.  I'm trying to find a method of commenting that will be quicker and easier to follow.  I've exported the notebook as pdf, then loaded it into Word and turned on comments.  
It can be found here in our Teams channel https://teradata.sharepoint.com/:w:/r/teams/ClearScapeDemo/Shared%20Documents/CSAE%20Jupyter%20Notebooks/Grocery_Recommendation/Review%20-%20Grocery_Recommendation_PY_SQL.pdf.docx?d=w4ebe0b45933e4cf3b180c764d2c39b85&csf=1&web=1&e=beQbQQ

**Review by DallasBowden — CHANGES_REQUESTED** [review]
Please see the document, https://teradata.sharepoint.com/:w:/r/teams/ClearScapeDemo/Shared%20Documents/CSAE%20Jupyter%20Notebooks/Grocery_Recommendation/Review%20-%20Grocery_Recommendation_PY_SQL.pdf.docx?d=w4ebe0b45933e4cf3b180c764d2c39b85&csf=1&web=1&e=beQbQQ

for my review comments.

**Review by DallasBowden — CHANGES_REQUESTED** [review]
1. Update Header.  Capitalize to "…Enhance Shopping Experiences".

2. Section 3 query doesn't run.  
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [21], in <cell line: 53>()
      2 SELECT NodeId, AmpId, Sequence, ObjectName, ObjectSize, RecordCount
---> 53 eng.execute(query)

AttributeError: 'Engine' object has no attribute 'execute'

**Comment by DallasBowden** [comment]
Please also update with Value Prop and Why Teradata in the Introduction.

**Review by DallasBowden — CHANGES_REQUESTED** [review]
1. Update "…from the Vantage tables" to "from Vantage tables".
2. This needs a Value Prop and Why Vantage in the Introduction.
3. Hide the library installation messages.
4. Section 3.2.  OperationalError: [Version 17.20.0.0] [Session 1118] [Teradata Database] [Error 3807] Object 'demo_user.RealEstate' does not exist.

**Comment by ForbiddenDevil** [comment]
Hi @DallasBowden ,

1. Update "…from the Vantage tables" to "from Vantage tables". **_(This phrase doesn't exist in the notebook)_**
2. Hide the library installation messages. **_(Library installation is already hidden using %%capture)_**
3. Update Header. Capitalize to "…Enhance Shopping Experiences". **_(Done)_**
4. This needs a Value Prop and Why Vantage in the Introduction. **_(Done)_**
5. Section 3.2. OperationalError: [Version 17.20.0.0] [Session 1118] [Teradata Database] [Error 3807] Object 'demo_user.RealEstate' does not exist. **_(This section doesn't exist in the notebook.)_**
6. AttributeError: 'Engine' object has no attribute 'execute' **_(Changed to execute_sql)_**

Please make sure that you are on branch **grocery_recommendation** and get the latest pull. The usecase path is _"UseCases/Grocery_Recommendation/Grocery_Recommendation_PY_SQL.ipynb"_

**Review by DallasBowden — APPROVED** [review]
Updated the spelling of 'preperation' to 'preparation'.

**Pull request merged**
