### PR TITLE
GraphAnalysis: Added new usecase

### PR DESCRIPTION
**Pull request by ForbiddenDevil**
@DougEbel Please review the new usecase.

### CODE REVIEW

**Comment by DougEbel** [comment]
Brick Wall:
select databasename, sql_lines  from gs_tables_db.ddl where databasename like 'DEMO_GraphAnalysis%' order by 1, seq

Empty result Set.

Also, tell me again how you are getting DDL data to the data storage.

**Comment by DougEbel** [comment]
I got down to 3. Visualization then got "NoSuchTableError "  

In the preceding steps there were executions of procedures followed by output of sample data that had no explanation.   It was  a long dry spell of meaningless numbers.  You might need to insert a graphic to describe Community, Centrality, closeness, etc.  I don't know if there is a plot that would be better than the table output, but at least you need some description of what the numbers mean.  

The directory name is: Graph_Analysis   but the notebook name is:  GraphSTO_PY_SQL.ipynb.   Following the pattern of other demos, the notebook would be named:  Graph_Analysis_PY_SQL.ipynb

**Comment by ForbiddenDevil** [comment]
@DougEbel Please review the incorporated changes. Thank you.

**Comment by DougEbel** [comment]
Fails on section 3 - create visualization.  Also, you ignored review comment above about naming of the notebook.

**Comment by DougEbel** [comment]
This ran on a new machine. Create a new pull request once you've done the following.  

1. In the intro, you need to look at the explanation you have after the graph and say what you are trying to accomplish ... marketing to key influencers as an example.  These are CDR records showing contacts between people.  If one person has more contacts with other people, then they may be key to influencing behavior.  The idea of "Communities" is vague until your describe it. 
2. The bubble graph is intriguing, however, the float over the bubbles isn't encouraged and the values shown when floating over the bubbles doesn't mean anything to me.   I don't know what X, Y, Centrality, or eiganvalue means. You need to translate terms into real world concepts. 

This can be a great demo to show people if they understand what it is doing.

**Comment by ForbiddenDevil** [comment]
@DougEbel Incorporated the changes suggested by you. Please review it once again. Thank you!

**Review by DougEbel — APPROVED** [review]
I'll approve this but the bubble graph needs improvement.  In your description you say:

The above **graph** displays the data in **graph** format. The nodes with larger size are the leader(influential) nodes i.e., with high eigenvector centrality. 

You need to walk the user through understanding it.  For example, community 8 in yellow near the top has 1 key influencer and is linked to (?) 9 other people.  Community 6 in purple near the top has 2 key influencers ... (meaning?) .  Community 1 in orange lacks key influencers ... (meaning?)

It would be great if the package doing the display had functionality like drag & drop or ability to put information on the pop-up in addition to customer ID ... such as the number of connections that make them a key influencer.

**Pull request merged**
