### PR TITLE
Chat with doc vantage version

### PR DESCRIPTION
**Pull request by chetan-hirapara**
Hi @DallasBowden @DougEbel 

Please review this PR.

Task: https://github.com/Teradata/jupyter-demos/issues/432

### CODE REVIEW

**Comment by DallasBowden** [comment]
Section 3, please is mis-spelled: Note: If you would like to skip the embedding generation step and move on to the next section, **pleasse** click [here] to skip.

Can we add in an estimated time to complete for this cell?  I timed it at 10 minutes.
image

The execution time for Section 6 only took a couple of seconds.

The section numbering drops to 4 after section 6.

Spelling in the sample questions:  **Wat** documents are required for Rental Car Excess?

**Comment by chetan-hirapara** [comment]
> Section 3, please is mis-spelled: Note: If you would like to skip the embedding generation step and move on to the next section, **pleasse** click [here] to skip.
> 
> Can we add in an estimated time to complete for this cell? I timed it at 10 minutes. image
> 
> The execution time for Section 6 only took a couple of seconds.
> 
> The section numbering drops to 4 after section 6.
> 
> Spelling in the sample questions: **Wat** documents are required for Rental Car Excess?

* @DallasBowden - Thanks Dallas, will add your suggestion asap.

**Comment by chetan-hirapara** [comment]
Hi @DallasBowden 

I have done your suggested changes to this PR, please review it again and merge

**Comment by DallasBowden** [comment]
Is there any way to hide the output from this cell?  I see that the --quiet parameter was used, but it's not stopping the messaging.  All that technical jargon may be confusing to the user and is, I assume, irrelevant for processing the use case.  Sometimes I get it, sometimes I don't.  I'm also getting it sometimes when I execute the cell that runs the chat panel.
"
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
"

**Comment by DallasBowden** [comment]
I also received an error when executing the cell to load the dataframe from read_document_content.  The error message is: 
"
NameError: name j'RecursiveCharacterTextSplitter' is not defined
"

I was able to resolve this in my notebook by adding the import statement:
from langchain.text_splitter import RecursiveCharacterTextSplitter

**Comment by chetan-hirapara** [comment]
* @DallasBowden - done, please take latest and check

**Comment by chetan-hirapara** [comment]
> Will the "huggingface/tokenizers" message always appear? If so, can we include a comment/description about what it means? image

Hi @DallasBowden 

This is intermitten issue, I have added code to hide it but it seems not working properly.
as suggestion from this, I've added this code: 
`os.environ["TOKENIZERS_PARALLELISM"] = "false"`
 
image

**Comment by chetan-hirapara** [comment]
Hi @DougEbel @DallasBowden 

I have done all the changes into this PR. please review it once

**Review by DallasBowden — APPROVED** [review]
This notebooks works as expected.  I will call-out that once you've skipped section 4 and then run section 5 to use the embeddings that have already been generated, you can't go back and run section 4 and skip section 5.  We can let this go for now.

**Pull request merged**
