### PR TITLE
Mortgage loan enhancement

### PR DESCRIPTION
**Pull request by ForbiddenDevil**
Currently this has outputs included. This requires OpenAI key to run this demo. It has a chatbot intrerface as well.

### CODE REVIEW

**Review by DallasBowden — CHANGES_REQUESTED** [review]
Step 3.2 does not have the RealEstate table created.

Object 'demo_user.RealEstate' does not exist.

**Comment by ForbiddenDevil** [comment]
Hi @DallasBowden , Please run the data_prep.ipynb before running the main notebook. Thanks.

**Review by DallasBowden — CHANGES_REQUESTED** [review]
1. Introduction - Update "…from the Vantage tables" to "from Vantage tables".
2. This needs a Value Prop and Why Vantage in the Introduction.
3. Hide the library installation messages.

Is this a question it should be able to answer?
image

**Comment by ForbiddenDevil** [comment]
The error in copy_to_sql() in this usecase is caused by downgraded pandas version:

image

If Pandas is upgraded to latest version, copy_to_sql() works with no issues.

After some debugging we found that azureml libraries are degrading pandas to 1.3.5

image

We need to discuss this. Energy_Consumption_AzureML is causing issues with other notebooks now.

**Review by DallasBowden — CHANGES_REQUESTED** [review]
There is a problem where you're joining the customer to the interest table:

```
q = """
    select c.FirstName, c.LastName, c.CreditScore, i.InterestRate 
      from Customer c 
           join Interest i 
           on c.CreditScore between i.MinCreditScore and i.MaxCreditScore
    where CustomerID=1001
"""

pd.read_sql(q, eng)
```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [25], in <cell line: 6>()
      1 q = """
      2     select c.FirstName, c.LastName, c.CreditScore, i.InterestRate from Customer c join Interest i on c.CreditScore between i.MinCreditScore and i.MaxCreditScore
      3     where CustomerID=1001
      4 """
----> 6 pd.read_sql(q, eng)

TypeError: __init__() got multiple values for argument 'schema'

**Comment by ForbiddenDevil** [comment]
This again is due to Energy_Consumption_Forecastin_AzureML notebook. It downgrades both numpy and pandas packages and hence causes issues with this notebook.

**Pull request merged**
