### PR TITLE
Fine tuning openAI model

### PR DESCRIPTION
**Pull request by vidhanbhonsle**
The demo notebook is about fine-tuning the OpenAI model.

### CODE REVIEW

**Review by DallasBowden — CHANGES_REQUESTED** [review]
1. Remove the space from the DEMO= statement in the QueryBand assignment.
2. There needs to be an introduction that relates this notebook to a problem that it can solve.  
3. There needs to be two other sections: Business Values and Why Vantage?
4. There needs to be a read-only version of this notebook.  Everyone will not have an openAPI key.
5. Show the status of the Fine-tuning job until it's complete.
6. Provide the results of the Tuning and allow the user to skip this tuning and continue the notebook without having to wait.
7. After all the trainings run, I'm asked to ask a question.  There's no help or indication of what type of question I should be asking.  Anything I ask get this as a response: "[{'role': 'system', 'content': 'You are a helpful and understanding assistant who can help with mental health issues. You are friendly and polite'}, {'role': 'user', 'content':"
8. Can the question and the response be combined into one cell so I don't have to execute another cell to get the answer?
9. The bottom is the first time I see any indication that this notebook is related to Mental Health.

[2024-01-17 Jupyter Notebook Guidelines.docx](https://github.com/Teradata/jupyter-demos/files/14729040/2024-01-17.Jupyter.Notebook.Guidelines.docx)

**Comment by vidhanbhonsle** [comment]
1. Remove the space from the DEMO= statement in the QueryBand assignment. 

> (Removed space)

2. There needs to be an introduction that relates this notebook to a problem that it can solve. 

> (Edited introduction) 

3. There needs to be two other sections: Business Values and Why Vantage? 

> (Added both the sections)

4. There needs to be a read-only version of this notebook. Everyone will not have an openAPI key. 

> (This I will create once the changes are approved)

5. Show the status of the Fine-tuning job until it's complete. 

> (Edited code to add the status of fine-tuning job)

6. Provide the results of the Tuning and allow the user to skip this tuning and continue the notebook without having to wait. 

> (OpenAI allows use of fine-tuned model through its fine-tuning APIs. User will have to use their own API key to see the results.)

7. After all the trainings run, I'm asked to ask a question. There's no help or indication of what type of question I should be asking. Anything I ask get this as a response: "[{'role': 'system', 'content': 'You are a helpful and understanding assistant who can help with mental health issues. You are friendly and polite'}, {'role': 'user', 'content':" 

> (Added a sample question to guide user and changed the response to only show answer )

8. Can the question and the response be combined into one cell so I don't have to execute another cell to get the answer?

> (Edited code to combine question and answer in one cell)

9. The bottom is the first time I see any indication that this notebook is related to Mental Health.

> (Added information of Mental Health dataset in introduction)

**Review by DallasBowden — CHANGES_REQUESTED** [review]
Thanks for making all the above changes.  The issues I'm having now is this:
1. Section 5.1 Hide the openAI key after it's been entered.
2. Section 5.3 
client = openai.OpenAI(api_key=api_key)
AttributeError: module 'openai' has no attribute 'OpenAI'

**Comment by vidhanbhonsle** [comment]
Hi Dallas,

1. Section 5.1 Hide the openAI key after it's been entered.
`I have added the getpass function`
3. Section 5.3
client = openai.OpenAI(api_key=api_key)
AttributeError: module 'openai' has no attribute 'OpenAI'
`The error is due to the version of openai, With the release of Version 1.0.0(https://pypi.org/project/openai/1.0.0/) on NOV 6, 2023 of openai API Python library, the way to call openai api has changed. I have added a note to tackle this.
`
thanks

**Review by DallasBowden — APPROVED** [review]
Execution has been verified.
Beta Introduction paragraph has been added to the top of the notebook.

**Pull request merged**
