### PR TITLE
Product Recommendation enhancement - both versions

### PR DESCRIPTION
**Pull request by chetan-hirapara**
Hi @DougEbel @DallasBowden 

Please review this PR# 

Task# https://github.com/Teradata/jupyter-demos/issues/446

Issues:
 * 7.5 Real time recommendation: 
     * Type the product name: throwing error
     * Giving same recommendations

### CODE REVIEW

**Comment by DallasBowden** [comment]
Let's re-word the description under the graph.  There's nothing attention grabbing here and no real surprises.  There's no reason to list the second observation because it's so obvious.  Instead, just call out:

The Candy chocolate isle has the highest number of products per isle (1246).
----------------------------------
The results for the products that we're searching for recommendations to go along with shouldn't contain the product itself:
Product Recommendations

Based on your search for **Pomegranate Gummy Bears** here are some recommended products:
**Pomegranate Gummy Bears**
Gummy Bears
Pomegranate Hard Candies
Organic Gummy Bears
Based on your search for **Sandies Pecan Shortbread Cookies** here are some recommended products:
**Sandies Pecan Shortbread Cookies**
Sandies Toffee Shortbread Cookies
Sandies Classic Shortbread Cookies
Pecan Shortbread Cookies
Based on your search for **Mac n' Cheese Puffs** here are some recommended products:
**Mac n' Cheese Puffs**
Cheese Puffs
Cheddar Puffs
Jumbo Cheese Puffs
In the above list we can see the recommendations for the searched product**s**.

**Comment by chetan-hirapara** [comment]
> Let's re-word the description under the graph. There's nothing attention grabbing here and no real surprises. There's no reason to list the second observation because it's so obvious. Instead, just call out:
> 
> ## The Candy chocolate isle has the highest number of products per isle (1246).
> The results for the products that we're searching for recommendations to go along with shouldn't contain the product itself: Product Recommendations
> 
> Based on your search for **Pomegranate Gummy Bears** here are some recommended products: **Pomegranate Gummy Bears** Gummy Bears Pomegranate Hard Candies Organic Gummy Bears Based on your search for **Sandies Pecan Shortbread Cookies** here are some recommended products: **Sandies Pecan Shortbread Cookies** Sandies Toffee Shortbread Cookies Sandies Classic Shortbread Cookies Pecan Shortbread Cookies Based on your search for **Mac n' Cheese Puffs** here are some recommended products: **Mac n' Cheese Puffs** Cheese Puffs Cheddar Puffs Jumbo Cheese Puffs In the above list we can see the recommendations for the searched product**s**.

* Hi @DallasBowden Thanks for the review. I will update the description of graph. Regarding product recommendations, it is due to we are searching same product in the database. 

**For example:** I have 6000 products in my DB, and I same searching exact keywords, so it is matching 100% and coming to the results. Do we need to remove those results which are 100% matching (distance=0.0)?

**Comment by DallasBowden** [comment]
The notebook "Recommendations_product_search_OpenAI_Python" is still returning the base product in the list of recommended products.
image

**Review by DallasBowden — CHANGES_REQUESTED** [review]
Both notebooks are still responding with the search item in the results.

**Comment by chetan-hirapara** [comment]
@DallasBowden - done, please take the latest code and test

**Review by DallasBowden — CHANGES_REQUESTED** [review]
The openAI notebook works as expected.
The openSource version will not populate the chart for "Distance measures between searched product and recommended product".
image

**Comment by chetan-hirapara** [comment]
> The openAI notebook works as expected. The openSource version will not populate the chart for "Distance measures between searched product and recommended product". image

* @DallasBowden - I have run the same notebook, it is working.  Could you please try into new machine? Have you run the file from top to down?

image

**Review by DallasBowden — CHANGES_REQUESTED** [review]
The OpenAI version works fine.  The only issue I have with it is that if I skip section 4 and go down to section 5, at some point I still have to go back up to section 4 to enter my key.  If the key is not needed, would it make more sense to move it down to the beginning of the section that requires it?

OpenSource version.  The Distance chart will populate now.  Searching for recommendations in 7.5 works for 1 word (syrup).  But not for 2 or more words.  I get an error message:

```
Generating the embeddings for:  Sea Salt Hummus Chips
100%
1/1 [00:00<00:00, 1.87it/s]
generate the embeddings for 1 search products:	 1.213202272017952
----- complete -----
Copy generated embeddings to SQL...
Calculating the distance between the searched snack and all snacks...
vector-distance calcuatation time:	 39.77101814901107
----- complete -----
Getting the recommendations...
new_search_product_embeddings_df shape:  (1, 1028)
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File /opt/conda/lib/python3.9/site-packages/pandas/core/indexes/range.py:414, in RangeIndex.get_loc(self, key)
    413 try:
--> 414     return self._range.index(new_key)
    415 except ValueError as err:

ValueError: 3 is not in range

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
File /opt/conda/lib/python3.9/site-packages/ipywidgets/widgets/widget_output.py:103, in Output.capture.<locals>.capture_decorator.<locals>.inner(*args, **kwargs)
    101     self.clear_output(*clear_args, **clear_kwargs)
    102 with self:
--> 103     return func(*args, **kwargs)

Input In [26], in btn_click(btn)
    112 f.value = 100
    113 f.layout.visibility = "hidden"
--> 114 html_op.value = response_template(
    115     df_recommandations, 1, number_of_recommendations
    116 )
    117 end = timeit.default_timer()
    118 load_time = end - start

Input In [21], in response_template(df, cnt, top_k)
     14 view2 = ""
     15 while j < i + top_k:
---> 16     product_name_recommended = df.loc[j, "product_name_recommended"]
     17     view2 = view2 + f""" <li>{product_name_recommended}</li>"""
     18     j += 1

File /opt/conda/lib/python3.9/site-packages/pandas/core/indexing.py:1146, in _LocationIndexer.__getitem__(self, key)
   1144     key = tuple(com.apply_if_callable(x, self.obj) for x in key)
   1145     if self._is_scalar_access(key):
-> 1146         return self.obj._get_value(*key, takeable=self._takeable)
   1147     return self._getitem_tuple(key)
   1148 else:
   1149     # we by definition only have the 0th axis

File /opt/conda/lib/python3.9/site-packages/pandas/core/frame.py:4012, in DataFrame._get_value(self, index, col, takeable)
   4006 engine = self.index._engine
   4008 if not isinstance(self.index, MultiIndex):
   4009     # CategoricalIndex: Trying to use the engine fastpath may give incorrect
   4010     #  results if our categories are integers that dont match our codes
   4011     # IntervalIndex: IntervalTree has no get_loc
-> 4012     row = self.index.get_loc(index)
   4013     return series._values[row]
   4015 # For MultiIndex going through engine effectively restricts us to
   4016 #  same-length tuples; see test_get_set_value_no_partial_indexing

File /opt/conda/lib/python3.9/site-packages/pandas/core/indexes/range.py:416, in RangeIndex.get_loc(self, key)
    414         return self._range.index(new_key)
    415     except ValueError as err:
--> 416         raise KeyError(key) from err
    417 if isinstance(key, Hashable):
    418     raise KeyError(key)

KeyError: 3

**Comment by DallasBowden** [comment]
I just created a new image and tested it again.  This time it worked for 1 and two search words, but not for 3.  Same error message as before:

```
Generating the embeddings for:  syrup
100%
1/1 [00:01<00:00, 1.54s/it]
generate the embeddings for 1 search products:	 2.212303127000041
----- complete -----
Copy generated embeddings to SQL...
Calculating the distance between the searched snack and all snacks...
vector-distance calcuatation time:	 40.90970963000018
----- complete -----
Getting the recommendations...
new_search_product_embeddings_df shape:  (1, 1028)
Total time to get the recommendation:	 134.70944157400004
----- complete -----
Generating the embeddings for:  Wheat Biscuits
100%
1/1 [00:00<00:00, 2.04it/s]
generate the embeddings for 1 search products:	 1.1827136740000697
----- complete -----
Copy generated embeddings to SQL...
Calculating the distance between the searched snack and all snacks...
vector-distance calcuatation time:	 41.42577153100001
----- complete -----
Getting the recommendations...
new_search_product_embeddings_df shape:  (1, 1028)
Total time to get the recommendation:	 114.2476325959999
----- complete -----
Generating the embeddings for:  Sea Salt Hummus Chips
100%
1/1 [00:00<00:00, 1.58it/s]
generate the embeddings for 1 search products:	 1.3258144470000843
----- complete -----
Copy generated embeddings to SQL...
Calculating the distance between the searched snack and all snacks...
vector-distance calcuatation time:	 42.09652550499982
----- complete -----
Getting the recommendations...
new_search_product_embeddings_df shape:  (1, 1028)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File /opt/conda/lib/python3.9/site-packages/pandas/core/indexes/range.py:414, in RangeIndex.get_loc(self, key)
    413 try:
--> 414     return self._range.index(new_key)
    415 except ValueError as err:

ValueError: 3 is not in range

The above exception was the direct cause of the following exception:

```

**Comment by chetan-hirapara** [comment]
> I just created a new image and tested it again. This time it worked for 1 and two search words, but not for 3. Same error message as before:
> 
> ```
> Generating the embeddings for:  syrup
> 100%
> 1/1 [00:01<00:00, 1.54s/it]
> generate the embeddings for 1 search products:	 2.212303127000041
> ----- complete -----
> Copy generated embeddings to SQL...
> Calculating the distance between the searched snack and all snacks...
> vector-distance calcuatation time:	 40.90970963000018
> ----- complete -----
> Getting the recommendations...
> new_search_product_embeddings_df shape:  (1, 1028)
> Total time to get the recommendation:	 134.70944157400004
> ----- complete -----
> Generating the embeddings for:  Wheat Biscuits
> 100%
> 1/1 [00:00<00:00, 2.04it/s]
> generate the embeddings for 1 search products:	 1.1827136740000697
> ----- complete -----
> Copy generated embeddings to SQL...
> Calculating the distance between the searched snack and all snacks...
> vector-distance calcuatation time:	 41.42577153100001
> ----- complete -----
> Getting the recommendations...
> new_search_product_embeddings_df shape:  (1, 1028)
> Total time to get the recommendation:	 114.2476325959999
> ----- complete -----
> Generating the embeddings for:  Sea Salt Hummus Chips
> 100%
> 1/1 [00:00<00:00, 1.58it/s]
> generate the embeddings for 1 search products:	 1.3258144470000843
> ----- complete -----
> Copy generated embeddings to SQL...
> Calculating the distance between the searched snack and all snacks...
> vector-distance calcuatation time:	 42.09652550499982
> ----- complete -----
> Getting the recommendations...
> new_search_product_embeddings_df shape:  (1, 1028)
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> File /opt/conda/lib/python3.9/site-packages/pandas/core/indexes/range.py:414, in RangeIndex.get_loc(self, key)
>     413 try:
> --> 414     return self._range.index(new_key)
>     415 except ValueError as err:
> 
> ValueError: 3 is not in range
> 
> The above exception was the direct cause of the following exception:
> ```

Hi @DallasBowden - resolve this error.

Please check it once.

**Comment by chetan-hirapara** [comment]
@DallasBowden - 

Regarding your suggestion: **The only issue I have with it is that if I skip section 4 and go down to section 5, at some point I still have to go back up to section 4 to enter my key. If the key is not needed, would it make more sense to move it down to the beginning of the section that requires it?**

- We required this key into section 4 and section 7.5
- I have added the message on top of section 7.5, so if user don't have the key then they can skip section 7.5
image

**Review by DallasBowden — APPROVED** [review]
Both notebooks work as expected.

**Pull request merged**
